### ISSUE TITLE
Cannot deserialize instance of `java.lang.String` out of START_OBJECT token

### ISSUE THREAD

**Issue by rhyek** [noelyahan/firestore-sink#2]
Hi. Using the following Python code to create a connector:
```python
requests.put(
    "http://{}/connectors/firestore-sink/config".format(
        kafka_connect_host),
    json={
        "task.max": 1,
        "plugin.path": "/usr/lib/firestore-sink.so",
        "configs": {
            "log.level": "TRACE",
            "encoding.key": "string",
            "encoding.value": "json",
            "topic": "debezium-pg.public.tasks",
            "firestore.collection.debezium-pg.public.tasks": "tasks",
            "firestore.delete.on.null.values": True,
            "firestore.project.id": "devops-lab-3-dev",
            "firestore.credentials.file.json": {
                ...
            }
        }
    },
)
```
I get the following error:
```
ERROR Uncaught exception in REST call to /connectors/firestore-sink/config (org.apache.kafka.connect.runtime.rest.errors.ConnectExceptionMapper)
 com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
  at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 39] (through reference chain: java.util.LinkedHashMap["configs"])
         at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
         at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
         at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1139)
         at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1093)
...etc
```

**Comment by rhyek** [comment]
Even this basic test fails with the exact same error:
```
curl --fail --show-error -X PUT http://localhost:8083/connectors/firestore-sink/config -H "Content-Type: application/json" -d '{
        "task.max": 1,
        "plugin.path": "/usr/lib/firestore-sink.so",
        "configs": {
            "log.level": "TRACE",
            "encoding.key": "string",
            "encoding.value": "json",
            "topic": "debezium-pg.public.tasks",
            "firestore.collection.debezium-pg.public.tasks": "tasks",
            "firestore.delete.on.null.values": True,
            "firestore.project.id": "devops-lab-3-dev"
        }
}'
```
On the other hand, something like this with the `configs` stringified and escaped:
```
curl --fail --show-error -X PUT http://localhost:8083/connectors/firestore-sink/config -H "Content-Type: application/json" -d '{
        "task.max": 1,
        "plugin.path": "/usr/lib/firestore-sink.so",
        "configs": "{\"log.level\":\"TRACE\",\"encoding.key\":\"string\",\"encoding.value\":\"json\",\"topic\":\"debezium-pg.public.tasks\",\"firestore.collection.debezium-pg.public.tasks\":\"tasks\",\"firestore.delete.on.null.values\":true,\"firestore.project.id\":\"devops-lab-3-dev\"}"
}'
```
I get the following response:
```json
{
   "error_code":400,
   "message":"Connector config {name=firestore-sink, plugin.path=/usr/lib/firestore-sink.so, configs={\"log.level\":\"TRACE\",\"encoding.key\":\"string\",\"encoding.value\":\"json\",\"topic\":\"debezium-pg.public.tasks\",\"firestore.collection.debezium-pg.public.tasks\":\"tasks\",\"firestore.delete.on.null.values\":true,\"firestore.project.id\":\"devops-lab-3-dev\"}, task.max=1} contains no connector type"
}
```
Not sure if that's referring to `connector.class`, but that key is not present on your example payload.

**Comment by rhyek** [comment]
Ok, nevermind. This doesn't seem to be a traditional Kafka Connect plugin and is more of a plugin for a plugin that runs on go and instructions are too unclear on how to use.

I think I'll just probably create a consumer from scratch.

**Comment by noelyahan** [comment]
@rhyek hi yes this a golang based kafka connector which follows same java connector specs, btw this is still developing as a internal project, hoping to release it to the community soon. Thanks for your interest
